= 序章

Spring Security 为基于 Java-EE 的企业级应用提供一种综合的解决方案。  

对于安全的讨论永不过时，系统安全非常重要。我们鼓励你采用"多安全层(layers of security)"的方式，每一层都负责一定范围内的安全性校验。每一层的校验越严格，你的应用就越安全、越健壮。  

在底层，你需要保证传输安全、处理系统认证，以减少中间人攻击。然后，你需要使用防火墙，也许还要配合使用VPNs或者IP安全来确保只有经过授权的系统可以接入和连接。在公共环境下，你需要部署DMZ，将面向公众的服务器与后台数据库、应用服务器隔离。你的操作系统也将扮演一个重要的部分，你需要解决例如非权限用户运行程序与文件系统安全性最大化这些问题。通常，操作系统也会拥有自己的防火墙配置。你还需要防范拒绝服务攻击和暴力系统攻击。入侵检测系统在这种情况下非常有用，它提供诸如实时拒绝某些异常的TCP/IP连接之类的功能。  

在更高层次，你的Java虚拟机最好为不同的Java类型配置不同的并且最小化的权限，同时，你的应用需要加入对于特定领域的安全配置。  

Spring Security 试图让这一层次 - 应用安全层 - 更加简单。  

当然，你需要妥善处理上面所提到的所有安全层，还要处理每一个安全层的管理要素。管理要素包括安全证书监控，修复缺陷，人员审查,审核，控制变更，系统项目管理，数据备份，灾难恢复，性能测评，负载监控，日志集中，事件响应程序等等...  

Spring Security 专注于帮助你的企业级应用层安全，你会发现在业务问题领域有很多不一样的需求。银行应用与电商应用的需要并不完全一样，电商应用与公司销售部门自动化工具的需要也不一样。这些定制的需求让应用安全变得非常有趣、具有挑战，非常值得。  

阅读《<<01-01,第一章 开始>>》，它是很好的起点。它会向你介绍此框架，并通过一个基于命名空间进行配置的示例带领你快速入门。关于 Spring Security 如何运作，以及一些常用的classes的更多信息，你可以参见《<<02,第二部分 架构与实现>>》。本部分剩余章节以传统的参考手册的风格来组织，方便用户在拥有一定的基础之后进行阅读。我们也建议您多阅读一些与应用安全问题相关的文档，Spring Security 不是能够解决所有安全问题的万能灵药。应用程序从设计开始就要伴随着安全性的考虑，这非常重要，试图改进它并非一个好主意。尤其是如果你在构建一个Web应用，你应该意识到很多诸如跨站脚本、伪造请求以及session劫持之类的潜在缺陷，你应该从一开始就仔细斟酌。 

http://www.owasp.org/[OWASP web 站点] 上保持前十的 web 应用漏洞清单是非常有用的参考信息。  

我们希望此参考手册对你有所帮助，我们也欢迎你提供反馈与建议。  

最后，由衷的欢迎你加入 Spring Security 社区。

include::01.Getting_Started.adoc[]

include::02.Introduction.adoc[]

include::03.What's_New_in_Spring_Security_4.1.adoc[]

include::04.Samples_and_Guides.adoc[]

include::05.Java_Configuration.adoc[]

include::06.Security_Namespace_Configuration.adoc[]

include::07.Sample_Applications.adoc[]

include::08.Spring_Security_Community.adoc[]