== Remember-Me认证

=== 综述

Remember-me或者持久登录认证指的是web站点能够在不同的sessions之间记住一个principal的凭证。传统的实现方式是将cookie发送到浏览器，cookie会被未来的sessions检查，并触发自动登录。Spring Security为此操作的发生提供必要的hooks，并且有两种具体的remember-me实现。一种使用哈希来保护基于cookie口令的安全，另一种使用数据库或者其它持久化存储机制来保存生成的口令。

注意两种实现都需要一个`UserDetailsService`。如果你正在使用一个认证provider，而它没有使用`UserDetailsService`（例如LDAP provider），那么remember-me就无法工作了，除非你在你的应用上下文中提供一个`UserDetailsService`。

=== 简单的基于哈希口令的方式

此方法使用哈希来实现有用的remember-me策略。本质上，cookie在成功的交互式认证时被发送到浏览器上，cookie可能像下面这样：

[source,text]
----
base64(username + ":" + expirationTime + ":" +
md5Hex(username + ":" + expirationTime + ":" password + ":" + key))

username:          As identifiable to the UserDetailsService
password:          That matches the one in the retrieved UserDetails
expirationTime:    The date and time when the remember-me token expires, expressed in milliseconds
key:               A private key to prevent modification of the remember-me token

----

remember-me token只在指定的周期中有效，并且提供的用户名与密码还有key不能改变。尤其是这存在一种潜在的安全问题，除非token到期，对于从任何用户代理获取的remember-me token都是可用的。同样的问题也存在于摘要认证。如果一个`principal`被知晓，token也被捕获，那么攻击者就能够很容易的改变用户的密码，并且立刻使所有的remember-me token无效。如果需要更重要的安全，你应该使用下一节描述的方法，或者简单的不再使用remember-me服务。

如果你熟悉命名空间配置那章的主题描述，你可以很简单的添加一个`<remember-me>`元素来启用remember-me认证。

[source,xml]
----
<http>
...
<remember-me key="myAppKey"/>
</http>

----

`UserDetailsService`通常会被自动选择。如果你的应用上下文中超过一个，你需要通过`user-service-ref`属性来指定使用哪一个，它的值是你的`UserDetailsService`bean的名字。

=== 持久化Token的方式

这一方式基于 http://jaspan.com/improved_persistent_login_cookie_best_practice 这篇文章，但也有一些小改动 [16]。为了通过命名空间配置使用这一方式，你应该添加一个数据源引用：

[source,xml]
----
<http>
...
<remember-me data-source-ref="someDataSource"/>
</http>

----

数据库应该包含一个`persistent_logins`表，它由下面的SQL（或者其它等价的SQL）创建：

[source,java]
----
create table persistent_logins (username varchar(64) not null,
                                series varchar(64) primary key,
                                token varchar(64) not null,
                                last_used timestamp not null)

----

=== Remember-Me接口与实现

Remember-me被与`UsernamePasswordAuthenticationFilter`一起使用，并且在`AbstractAuthenticationProcessingFilter`的子类中由hooks实现。它也在`BasicAuthenticationFilter`中被使用。hooks会在适当的时间调用具体的`RememberMeServices`。此接口像这样：

[source,java]
----
Authentication autoLogin(HttpServletRequest request, HttpServletResponse response);

void loginFail(HttpServletRequest request, HttpServletResponse response);

void loginSuccess(HttpServletRequest request, HttpServletResponse response,
    Authentication successfulAuthentication);

----

方法中做了什么可以参考JavaDocs，虽然在这里我们看到`AbstractAuthenticationProcessingFilter`只调用了`loginFail()`和`loginSuccess()`方法。在`SecurityContextHolder`没有包含一个`Authentication`时，`autoLogin()`方法由`RememberMeAuthenticationFilter`调用。因此，这个接口提供了根本的remember-me实现，它有足够多的与认证相关的事件的通知，并且说明了无论何时，候选的web请求都可能包含一个cookie，并且期望被记住。这一设计允许任意数量的remember-me实现策略。我们在上面看到Spring Security提供了两种实现。我们会依次介绍它们。

==== TokenBasedRememberMeServices

此实现支持简单的方法，它被描述在 http://docs.spring.io/spring-security/site/docs/4.1.3.RELEASE/reference/htmlsingle/#remember-me-hash-token[17.2节_简单的基于哈希口令的方式]。`TokenBasedRememberMeServices`生成一个`RememberMeAuthenticationToken`，它被`RememberMeAuthenticationProvider`处理。一个键值在这个认证provider和`TokenBasedRememberMeServices`共享。另外，`TokenBasedRememberMeServices`需要一个`UserDetailsService`，它可以重新获取用户名和密码，并对签名进行比较，然后生成`RememberMeAuthenticationToken`来包含正确的`GrantedAuthority`s。一些注销命令的顺序应该被通过应用来提供，如果用户做了请求，那么cookie就会无效。`TokenBasedRememberMeServices`也实现了Spring Security的`LogoutHandler`接口，因此可以使用`LogoutFilter`来自动清理cookie。

应用上下文中启用remember-me服务，那么需要一些beans：

[source,xml]
----
<bean id="rememberMeFilter" class=
"org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter">
<property name="rememberMeServices" ref="rememberMeServices"/>
<property name="authenticationManager" ref="theAuthenticationManager" />
</bean>

<bean id="rememberMeServices" class=
"org.springframework.security.web.authentication.rememberme.TokenBasedRememberMeServices">
<property name="userDetailsService" ref="myUserDetailsService"/>
<property name="key" value="springRocks"/>
</bean>

<bean id="rememberMeAuthenticationProvider" class=
"org.springframework.security.authentication.RememberMeAuthenticationProvider">
<property name="key" value="springRocks"/>
</bean>

----

不要忘了使用`UsernamePasswordAuthenticationFilter.setRememberMeServices()`，并将`RememberMeServices`作为参数传递进去，将`RememberMeAuthenticationProvider`包含到你的`AuthenticationManager.setProviders()`列表，并添加`RememberMeAuthenticationFilter`到你的`FilterChainProxy`（通常紧跟着`UsernamePasswordAuthenticationFilter`之后）。

==== PersistentTokenBasedRememberMeServices

这个类可以像`TokenBasedRememberMeServices`一样的方式被使用，但它还需要配置一个`PersistentTokenRepository`来存储tokens。有两个标准：

*   `InMemoryTokenRepositoryImpl` 这个只用于测试
*   `JdbcTokenRepositoryImpl` 将tokens保存到数据库中
数据库schema在 http://docs.spring.io/spring-security/site/docs/4.1.3.RELEASE/reference/htmlsingle/#remember-me-persistent-token[17.3节 持久化口令的方式]中被描述。

[16] 本质上，用户名不会被包含在cookie中，这样可以预防非必须但有效登录名被暴露。这被描述在本文的讨论小节。